# Generated by Django 5.2.9 on 2025-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_id", models.IntegerField(unique=True)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("province", models.CharField(max_length=50)),
                ("work_sector", models.CharField(max_length=50)),
                ("tenure", models.IntegerField()),
                (
                    "churn_risk",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Low",
                        max_length=10,
                    ),
                ),
                ("churn_prob", models.FloatField(default=0)),
                ("risk_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
