# Generated by Django 5.2.9 on 2025-12-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("done_by", models.CharField(max_length=100)),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("table_affected", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="churn_prob",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="churn_risk",
            field=models.CharField(default="Low", max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cust_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="province",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="work_sector",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="CustomerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField()),
                ("activity_type", models.CharField(max_length=100)),
                ("details", models.TextField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="dashboard.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSeriesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_ref", models.DateField()),
                ("total_transactions", models.IntegerField()),
                ("balance_avg", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.customer",
                    ),
                ),
            ],
        ),
    ]
