# Generated by Django 5.2.9 on 2025-12-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_auditlog_remove_customer_churn_prob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="churn_prob",
            field=models.FloatField(default=0.0),
        ),
    ]
