# Generated by Django 5.2.9 on 2025-12-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_customer_churn_prob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeractivity",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="customeractivity",
            name="details",
        ),
        migrations.RemoveField(
            model_name="timeseriessummary",
            name="balance_avg",
        ),
        migrations.RemoveField(
            model_name="timeseriessummary",
            name="total_transactions",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="active_product_category_nbr",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="cc_transaction_all_amt",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="cc_transaction_all_cnt",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="mobile_eft_all_amt",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="mobile_eft_all_cnt",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="active_product_category_nbr_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="cc_transaction_all_amt_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="cc_transaction_all_cnt_trend",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="cc_transaction_all_cnt_trend_3m",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="mobile_eft_all_amt_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="mobile_eft_all_cnt_mean_3m",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="mobile_eft_all_cnt_trend",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="mobile_eft_all_cnt_trend_3m",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="mobile_to_card_ratio_amt",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="timeseriessummary",
            name="months_since_last_txn",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="work_sector",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
